# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35d598482b908a64543742824c681bfb85642fec744868002784ca381b95d3fe4f7d4865454f628586017d6828fd35f207928145338d3ecdb23725564aba95f3

test:
  secret_key_base: 29ba3811fb70cae1ec8b2e9f699b47bb6e1979edd1a3965ff864af9f5f4a8bb169f50cffb5fc0af5ffac8304c4f9d9cbbea5c020170c9fdd19ce459736fcc646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
